version: 2.1

steps:
  - run: &install_dependencies
      name: Install Dependencies
      command: pip install -r src/requirements.txt
  - run: &test
      name: Test
      command: pytest


jobs:
  launch_tests:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: *install_dependencies
      - run: *test
  launch_integration_tests:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: *install_dependencies
      - run:
          name: Running end-to-end integration tests
          command: echo "Put integration tests here"
  deploy_staging:
    docker:
      - image: cimg/python:3.9
    environment:
      ENV_NAME: staging
    steps:
      - run:
          name: Running deployment to staging step
          command: echo "Deploy to staging"
  deploy_production:
    docker:
      - image: cimg/python:3.9
    environment:
      ENV_NAME: production
    steps:
      - run:
          name: Running deployment to production step
          command: echo "Deploy to production"

workflows:
  run_tests_and_deploy: 
    jobs: 
      - launch_tests: 
          context:
            - test_configuration_python
          filters:
            branches:
              ignore: /branching\/.*/
      - launch_integration_tests: 
          context:
            - test_configuration_python
          filters:
            branches:
              only: /branching\/.*/
      - deploy_staging: 
          context:
            - staging
          filters: 
            branches:
              only: branching-staging
      - deploy_production: 
          context:
            - production
          filters: 
            branches:
              only: branching-production
